### ISSUE TITLE
Data

### ISSUE THREAD

**Issue by wanrick** [wanrick/COS301-TeamNature#10]
-Design data module according to specs

**Comment by Regan-Koopmans** [comment]
In branch `regan` I have added a file named `Data.tex`. This file contains what I think the structure of the Data Module may look like in  the document.

I have added a number of sections, with comments motivating the need for these sections, and what their content may entail for anyone who does future work.

I am open to any comments about these subtasks/paragraphs, and encourage any comments about what I have proposed. These are simply my ideas thusfar, and will not take offense if people think they are superflouous or wrong for the paper we are writting.

Otherwise, if everyone is happy with the sections I have proposed, I will close this issue and create new ones based on the paragraphs I have proposed in the new file.

Thanks!
